name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Composer Dependencies
        uses: ramsey/composer-install@1.3.0
      - name: PHPCS Code Review
        uses: rtCamp/action-phpcs-code-review@v2.0.4
      - name: PHPStan (php-actions)
        uses: php-actions/phpstan@v2
